### ISSUE TITLE
hoverColor property for captions and labels not working

### ISSUE THREAD

**Issue by GrandMagus02** [kurkle/chartjs-chart-treemap#149]
So hoverColor property for captions and labels not working. Color field works as expected but hoverColor is not. I found that using a function it is being called but the return value make nothing.

**Comment by stockiNail** [comment]
@GrandMagus02  I have already submitted a PR to fix it.  #150

**Comment by kurkle** [comment]
Interestingly this works: `color: (ctx) => ctx.active ? 'white' : 'black',`

**Comment by kurkle** [comment]
Hover options are disabled for subResolvers (so labels, captions etc).
https://github.com/chartjs/Chart.js/blob/c849b7bc1d974c3e760c69afb32aaa0f9201aba4/src/core/core.config.js#L374

It seems this originates back to https://github.com/chartjs/Chart.js/pull/8374 and I do not recall at all why.

**Comment by stockiNail** [comment]
> Interestingly this works: `color: (ctx) => ctx.active ? 'white' : 'black',`

This is working as workaround because you are setting directly `color` and not `hoverColor`. 
I have some doubts about fallback you mentioned because the controller is testing if the element is active and then use `color` or `hoverColor` (the same for font).

https://github.com/kurkle/chartjs-chart-treemap/blob/6953f29a23653a73a74094b0f4f2e83809a6ef8e/src/element.js#L129

https://github.com/kurkle/chartjs-chart-treemap/blob/6953f29a23653a73a74094b0f4f2e83809a6ef8e/src/element.js#L190

This is also the reason why in the PR I'm adding `active` property to the bounding rects.

**Comment by stockiNail** [comment]
Before version 2.1.0, it worked because the controller was doing those tests and we passed the element to draw labels/captions functions where `active` property was present. In version 2.1.0 we have changed the calculation for borderWidth/borderRadius following the bar element of Chart.js and we passed the inner bounding rect (without `active`) to draw functions .

**Comment by kurkle** [comment]
Ok, played around with Chart.js code and it seems the `hover` filtering is a workaround for infinite recursion.

By default, hoverColor (for example) is scriptable, which reads `color` from the same scope, and that resolves to `hoverColor` which then again reads `color`.. and so on.  It should be fixed for chart.js v4, but we need to work around it here. I guess your PR is as good as it gets :)
